import type { ReactNode } from 'react';
import { Link, useNavigate } from 'react-router';
import { Heart, MapPin, Package, Settings2, Sparkles, RotateCcw, Navigation, ChevronRight } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useCart } from '../contexts/CartContext';
import { products } from '../data/products';
import { toast } from 'sonner';

const money = (n: number) => `R$ ${n.toFixed(2).replace('.', ',')}`;
export function Planner({ mode = 'profile' }: { mode?: 'profile' | 'favorites' | 'orders' }) {
  const { user } = useAuth(); const { orderHistory, addToCart } = useCart(); const nav = useNavigate();
  const favoriteIds = JSON.parse(localStorage.getItem('uvafood_favorites') ?? '[]') as string[];
  const favorites = products.filter(p => favoriteIds.includes(p.id));
  const repeat = (items: typeof orderHistory[number]['items']) => { items.forEach(addToCart); toast.success('Itens adicionados ao carrinho'); nav('/carrinho'); };
  const title = mode === 'favorites' ? 'Seus favoritos' : mode === 'orders' ? 'Pedidos e rastreio' : `Olá, ${user?.name?.split(' ')[0] ?? 'cliente'}`;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">Sua área UVA</p><h1 className="font-[Fraunces] text-4xl font-bold tracking-[-.045em] text-[#35130c]">{title}</h1><p className="mt-2 text-muted-foreground">Seu delivery, do seu jeito — sempre perto.</p></div><Link to="/cardapio" className="inline-flex items-center gap-2 self-start rounded-full bg-[#35130c] px-5 py-3 text-sm font-bold text-white">Explorar cardápio <ChevronRight className="size-4" /></Link></div>
  {mode === 'profile' && <><div className="grid gap-4 md:grid-cols-3"><article className="rounded-3xl bg-[#35130c] p-6 text-white shadow-lg"><Sparkles className="mb-8 size-6 text-[#ffdb74]" /><p className="text-sm text-white/65">Seu benefício de hoje</p><h2 className="mt-1 font-[Fraunces] text-2xl">Frete grátis no próximo combo</h2><p className="mt-3 text-sm text-white/70">Use o cupom <b className="text-[#ffdb74]">BEMVINDO</b> até domingo.</p></article><article className="rounded-3xl border border-border bg-card p-6"><MapPin className="mb-7 size-6 text-primary" /><p className="text-sm text-muted-foreground">Endereço principal</p><h2 className="mt-1 text-lg font-bold">Casa — Ipanema</h2><p className="mt-2 text-sm text-muted-foreground">Rua Visconde de Pirajá, 420</p></article><article className="rounded-3xl border border-border bg-card p-6"><Settings2 className="mb-7 size-6 text-primary" /><p className="text-sm text-muted-foreground">Preferências</p><h2 className="mt-1 text-lg font-bold">Sem cebola, por favor</h2><button className="mt-3 text-sm font-bold text-primary">Editar preferências</button></article></div><section className="mt-10"><h2 className="mb-4 text-xl font-bold">Atalhos do seu planner</h2><div className="grid gap-3 sm:grid-cols-3">{[{to:'/pedidos', icon:Package, label:'Acompanhar pedidos', text:`${orderHistory.length} pedidos no histórico`},{to:'/favoritos', icon:Heart,label:'Favoritos',text:`${favorites.length} escolhas salvas`},{to:'/mapa',icon:Navigation,label:'Área de entrega',text:'Veja bairros atendidos'}].map(({to,icon:Icon,label,text})=><Link key={to} to={to} className="group flex items-center gap-4 rounded-2xl border border-border bg-white p-4 transition hover:-translate-y-0.5 hover:border-primary/30"><span className="grid size-11 place-items-center rounded-xl bg-secondary text-primary"><Icon className="size-5" /></span><span><b className="block text-sm">{label}</b><small className="text-muted-foreground">{text}</small></span><ChevronRight className="ml-auto size-4 text-muted-foreground transition group-hover:translate-x-1" /></Link>)}</div></section></>}
  {mode === 'favorites' && <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{favorites.length ? favorites.map(p => <article key={p.id} className="overflow-hidden rounded-3xl border border-border bg-white"><img src={p.image} alt={p.name} className="h-40 w-full object-cover" /><div className="p-5"><p className="text-xs font-bold text-primary">{p.category}</p><h2 className="mt-1 font-bold">{p.name}</h2><div className="mt-4 flex items-center justify-between"><b>{money(p.price)}</b><button onClick={() => { addToCart(p); toast.success('Adicionado ao carrinho'); }} className="rounded-full bg-[#35130c] px-4 py-2 text-xs font-bold text-white">Pedir de novo</button></div></div></article>) : <Empty icon={<Heart />} title="Sua lista está esperando" text="Salve pratos com o coração para reencontrá-los aqui." />}</section>}
  {mode === 'orders' && <section className="space-y-3">{orderHistory.length ? orderHistory.map(order => <article key={order.id} className="rounded-2xl border border-border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Pedido {order.id}</p><p className="text-sm text-muted-foreground">{order.date} · {order.items.length} itens</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{order.status}</span></div><div className="mt-4 flex items-center justify-between border-t border-border pt-4"><b>{money(order.total)}</b><div className="flex gap-2"><Link to="/mapa" className="rounded-full border border-border px-3 py-2 text-xs font-bold">Rastrear</Link><button onClick={() => repeat(order.items)} className="inline-flex items-center gap-1 rounded-full bg-[#35130c] px-3 py-2 text-xs font-bold text-white"><RotateCcw className="size-3" /> Repetir</button></div></div></article>) : <Empty icon={<Package />} title="Nenhum pedido ainda" text="Quando bater a fome, seu histórico aparece aqui." />}</section>}
  </main>;
}
function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}) { return <div className="grid min-h-72 place-items-center rounded-3xl border border-dashed border-border bg-secondary/40 text-center"><div><span className="mx-auto mb-4 grid size-14 place-items-center rounded-2xl bg-white text-primary">{icon}</span><h2 className="font-[Fraunces] text-2xl font-bold">{title}</h2><p className="mt-2 max-w-xs text-sm text-muted-foreground">{text}</p></div></div>; }
